### ISSUE TITLE
--ntp-server 

### ISSUE THREAD

**Issue by RandomStudentA** [rwth-ti/gr-localization#1]
Ubantu 16.04 
Swig 3.0.12 
![capture](https://user-images.githubusercontent.com/37094035/38550317-ba0f9640-3ce8-11e8-887d-2d381c25d3b9.PNG)

I'm a studenting trying to do this for a school project and I don't really have any knowledge on this area. This is the error it's giving me , I'm not sure how to fix it.

**Comment by johschmitz** [comment]
I don't see the full error message because you have cut it but I believe that you have to use a more recent version of gnuradio. The interface has changed and that particular argument is needed for this project in order to avoid that the receiver just starts to run when you start the program. So try using a more recent gnuradio version.

**Comment by RandomStudentA** [comment]
Yep , after updating the GNU radio its working ( I think ).
