### ISSUE TITLE
Error downloading map

### ISSUE THREAD

**Issue by RandomStudentA** [rwth-ti/gr-localization#2]
It's me again. Orz Now that I've gotten the commands to work , but since I currently have only one USRP I'm not sure if what I'm doing to is correct , but anyhow the current visible issue to me is that the map is not showing up and I'm getting error downloading it. 
![capture](https://user-images.githubusercontent.com/37094035/38597249-16c2efb8-3d89-11e8-945c-ad9c591eefef.PNG)

**Comment by johschmitz** [comment]
I think you probably have to create the folders for log and map otherwise it can't write to them. I am traveling this week so I can't check myself right now.

**Comment by RandomStudentA** [comment]
I added sudo infornt of the gui and a map appeared , but its not the place I'm at so I tried to self localization it to find my coordinated but the error appears, am I doing something wrong? 
![capture](https://user-images.githubusercontent.com/37094035/38599176-efaa1452-3d91-11e8-823c-8a753ed5ae74.PNG)

**Comment by johschmitz** [comment]
Self localization is not what you want to do, that is to calibrate the sensor locations.

For the map you have to edit the bounding box of the area that you want to look at, either in the GUI or in the code to make it permanent.

**Comment by johschmitz** [comment]
By the way if you have to run it with sudo then you're doing something wrong. When everything is set up correctly it will definitely run without sudo.

**Comment by RandomStudentA** [comment]
I went to make 2 folder called maps and map( I'm not sure if it affected it but it works now). 
![capture](https://user-images.githubusercontent.com/37094035/38600364-7b0c2ed2-3d96-11e8-80d9-34f39571160d.PNG)

**Comment by RandomStudentA** [comment]
I can now start it without problems but when I manually try to type in the coordinate it still gives me error 
![capture](https://user-images.githubusercontent.com/37094035/38600566-345c66d6-3d97-11e8-9083-daf1b0a819ec.PNG)

**Comment by johschmitz** [comment]
Can you see if the downloaded map is in the maps folder that you created?
Another option is to find the error message in the python code and debug, for example with some prints and find out where exactly it crashes. I think this part is inside a "try" so that's why you don't see the line where it crashes. So you can try to comment the try for a moment.

**Comment by RandomStudentA** [comment]
Nope its not the in folder I created , I created it at apps/maps/map , I'm not sure if its suppose to be there.  I'll try to look into the code and see if I can figure something out.

**Comment by johschmitz** [comment]
Not in apps just in the gr-localization root folder. But I just checked and saw that both folders are there by default when you clone the repository. So maybe something is wrong with your folder rights or ownership. Otherwise I don't see right now why you should get an io error with permission denied as shown in your first message. Did you clone it with sudo or something like that? Then I would recommend you to just start over with a fresh copy from github.

**Comment by RandomStudentA** [comment]
I found the maps folder with the default location and not the location I wanted. As for the file itself I'm not sure since it was installed by the previous people who didn't finish the project , but anyhow I think I would just install a fresh copy and hope its smooth sailing from there on.

**Comment by RandomStudentA** [comment]
I successfully re downloaded it and it works now.
![capture](https://user-images.githubusercontent.com/37094035/38603055-1fb1e64a-3d9f-11e8-8fb9-34f767bb2f89.PNG)
The next question isn't related but I'm confused on how its suppose to work , since it shows the ip that I'm running in local , assuming I get another PC and the hardware how would they detect where each other is?

**Comment by johschmitz** [comment]
Looks like your bounding box is a bit large maybe? Anyways you should have one computer per receiver and they should be somehow connected in a way that they are in the same network. But more important is to get a good clock synchronization, for example with a GPSDO. We used LEA M8F in the end in TMODE2. But for that you slightly need to modify UHD so that the USRP accepts the other GPS. We also reconfigured the GPS chip with the ublox software to have an NMEA stream similar to the Jackson Labs/Ettus LCXO GPSDO. Good luck. See the pcb reference design from the open digital radio guys.
https://www.opendigitalradio.org/lea-m8f-gpsdo

**Comment by RandomStudentA** [comment]
I see thank you.
